#HelloTheWorld:
#    path:       /hello-world
#    defaults:   { _controller: BlogBundle:Blog:index }
#
#ByebyeWorld:
#    path:       /byebye-world
#    defaults:   { _controller: BlogBundle:Blog:quit }

    
blog_index:
    path:      /{page}
    defaults:  { _controller: BlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d*
    
blog_read:
    path:      /article/{id}
    defaults:  { _controller: BlogBundle:Blog:read }
    requirements:
        id:    \d+
    
blog_read_slug:
    path:       /{year}/{slug}.{format}
    defaults:   { _controller: BlogBundle:Blog:readSlug, format: html }
    requirements:
        year:   \d{4}
        format: html|xml
    
blog_add:
    path:      /add
    defaults:  { _controller: BlogBundle:Blog:add }
    
blog_modify:
    path:       /modify/{id}
    defaults:   { _controller: BlogBundle:Blog:modify }
    requirements:
          id:   \d+
          
blog_delete:
    path:       /delete/{id}
    defaults:   { _controller: BlogBundle:Blog:delete }
    requirements:
          id:   \d+
    